# Generated by Django 5.2.3 on 2025-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JabonFloral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jabón Floral',
                'verbose_name_plural': 'Jabones Florales',
            },
        ),
        migrations.CreateModel(
            name='JabonFrutal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jabón Frutal',
                'verbose_name_plural': 'Jabones Frutales',
            },
        ),
        migrations.CreateModel(
            name='JabonPlayero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Jabón Playero',
                'verbose_name_plural': 'Jabones Playeros',
            },
        ),
    ]
