# Generated by Django 5.2.3 on 2025-07-13 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecosmetic_Inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabonfloral',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jabonfrutal',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jabonplayero',
            options={},
        ),
    ]
