# Generated by Django 5.2.4 on 2025-07-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecosmetic_Inventario', '0002_alter_jabonfloral_options_alter_jabonfrutal_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jabonfloral',
            options={'ordering': ['nombre'], 'verbose_name': 'Jabón Floral', 'verbose_name_plural': 'Jabones Florales'},
        ),
        migrations.AlterModelOptions(
            name='jabonfrutal',
            options={'ordering': ['nombre'], 'verbose_name': 'Jabón Frutal', 'verbose_name_plural': 'Jabones Frutales'},
        ),
        migrations.AlterModelOptions(
            name='jabonplayero',
            options={'ordering': ['nombre'], 'verbose_name': 'Jabón Playero', 'verbose_name_plural': 'Jabones Playeros'},
        ),
        migrations.AlterField(
            model_name='jabonfloral',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='jabonfloral',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jabonfloral',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='jabonfrutal',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='jabonfrutal',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jabonfrutal',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='jabonplayero',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='jabonplayero',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jabonplayero',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
    ]
